// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.2
// source: protocols.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClientPublishMessage is sent by a client to publish a message to a topic.
// Used with the ClientPublishProtocol.
type ClientPublishMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientPublishMessage) Reset() {
	*x = ClientPublishMessage{}
	mi := &file_protocols_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientPublishMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPublishMessage) ProtoMessage() {}

func (x *ClientPublishMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPublishMessage.ProtoReflect.Descriptor instead.
func (*ClientPublishMessage) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{0}
}

func (x *ClientPublishMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ClientPublishMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ClientPushMessage is sent by the server to push a message to a subscribed client.
// Used with the ClientPushProtocol.
type ClientPushMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Sender        []byte                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientPushMessage) Reset() {
	*x = ClientPushMessage{}
	mi := &file_protocols_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientPushMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPushMessage) ProtoMessage() {}

func (x *ClientPushMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPushMessage.ProtoReflect.Descriptor instead.
func (*ClientPushMessage) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{1}
}

func (x *ClientPushMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ClientPushMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ClientPushMessage) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

// ClientSubscribeMessage is sent by a client to subscribe or unsubscribe from a topic.
// Used with the ClientSubscribeProtocol.
type ClientSubscribeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Subscribe     bool                   `protobuf:"varint,2,opt,name=subscribe,proto3" json:"subscribe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSubscribeMessage) Reset() {
	*x = ClientSubscribeMessage{}
	mi := &file_protocols_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSubscribeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSubscribeMessage) ProtoMessage() {}

func (x *ClientSubscribeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSubscribeMessage.ProtoReflect.Descriptor instead.
func (*ClientSubscribeMessage) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{2}
}

func (x *ClientSubscribeMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ClientSubscribeMessage) GetSubscribe() bool {
	if x != nil {
		return x.Subscribe
	}
	return false
}

// ClientSubscriptionsMessage contains the list of topics a client is subscribed to.
// Used with the ClientSubscriptionsProtocol.
type ClientSubscriptionsMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []string               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSubscriptionsMessage) Reset() {
	*x = ClientSubscriptionsMessage{}
	mi := &file_protocols_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSubscriptionsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSubscriptionsMessage) ProtoMessage() {}

func (x *ClientSubscriptionsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSubscriptionsMessage.ProtoReflect.Descriptor instead.
func (*ClientSubscriptionsMessage) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{3}
}

func (x *ClientSubscriptionsMessage) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

// ClientAddrRequestMessage is sent by a client to request the addresses of another peer.
// Used with the ClientAddrProtocol.
type ClientAddrRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // peer.ID serialized as bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientAddrRequestMessage) Reset() {
	*x = ClientAddrRequestMessage{}
	mi := &file_protocols_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAddrRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAddrRequestMessage) ProtoMessage() {}

func (x *ClientAddrRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAddrRequestMessage.ProtoReflect.Descriptor instead.
func (*ClientAddrRequestMessage) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{4}
}

func (x *ClientAddrRequestMessage) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

// ClientAddrResponseMessage is the response containing the multiaddresses of a peer or an error.
// Used with the ClientAddrProtocol.
type ClientAddrResponseMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ClientAddrResponseMessage_Success_
	//	*ClientAddrResponseMessage_Error
	Result        isClientAddrResponseMessage_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientAddrResponseMessage) Reset() {
	*x = ClientAddrResponseMessage{}
	mi := &file_protocols_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAddrResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAddrResponseMessage) ProtoMessage() {}

func (x *ClientAddrResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAddrResponseMessage.ProtoReflect.Descriptor instead.
func (*ClientAddrResponseMessage) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{5}
}

func (x *ClientAddrResponseMessage) GetResult() isClientAddrResponseMessage_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ClientAddrResponseMessage) GetSuccess() *ClientAddrResponseMessage_Success {
	if x != nil {
		if x, ok := x.Result.(*ClientAddrResponseMessage_Success_); ok {
			return x.Success
		}
	}
	return nil
}

func (x *ClientAddrResponseMessage) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*ClientAddrResponseMessage_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isClientAddrResponseMessage_Result interface {
	isClientAddrResponseMessage_Result()
}

type ClientAddrResponseMessage_Success_ struct {
	Success *ClientAddrResponseMessage_Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type ClientAddrResponseMessage_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"` // Error message, e.g., "peer not found"
}

func (*ClientAddrResponseMessage_Success_) isClientAddrResponseMessage_Result() {}

func (*ClientAddrResponseMessage_Error) isClientAddrResponseMessage_Result() {}

type ClientAddrResponseMessage_Success struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addrs         [][]byte               `protobuf:"bytes,1,rep,name=addrs,proto3" json:"addrs,omitempty"` // multiaddrs serialized as bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientAddrResponseMessage_Success) Reset() {
	*x = ClientAddrResponseMessage_Success{}
	mi := &file_protocols_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAddrResponseMessage_Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAddrResponseMessage_Success) ProtoMessage() {}

func (x *ClientAddrResponseMessage_Success) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAddrResponseMessage_Success.ProtoReflect.Descriptor instead.
func (*ClientAddrResponseMessage_Success) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ClientAddrResponseMessage_Success) GetAddrs() [][]byte {
	if x != nil {
		return x.Addrs
	}
	return nil
}

var File_protocols_proto protoreflect.FileDescriptor

const file_protocols_proto_rawDesc = "" +
	"\n" +
	"\x0fprotocols.proto\x12\x02pb\"@\n" +
	"\x14ClientPublishMessage\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"U\n" +
	"\x11ClientPushMessage\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\fR\x06sender\"L\n" +
	"\x16ClientSubscribeMessage\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tsubscribe\x18\x02 \x01(\bR\tsubscribe\"4\n" +
	"\x1aClientSubscriptionsMessage\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topics\"*\n" +
	"\x18ClientAddrRequestMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"\xa1\x01\n" +
	"\x19ClientAddrResponseMessage\x12A\n" +
	"\asuccess\x18\x01 \x01(\v2%.pb.ClientAddrResponseMessage.SuccessH\x00R\asuccess\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x1a\x1f\n" +
	"\aSuccess\x12\x14\n" +
	"\x05addrs\x18\x01 \x03(\fR\x05addrsB\b\n" +
	"\x06resultB.Z,github.com/martonp/tatanka-mesh/protocols/pbb\x06proto3"

var (
	file_protocols_proto_rawDescOnce sync.Once
	file_protocols_proto_rawDescData []byte
)

func file_protocols_proto_rawDescGZIP() []byte {
	file_protocols_proto_rawDescOnce.Do(func() {
		file_protocols_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocols_proto_rawDesc), len(file_protocols_proto_rawDesc)))
	})
	return file_protocols_proto_rawDescData
}

var file_protocols_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protocols_proto_goTypes = []any{
	(*ClientPublishMessage)(nil),              // 0: pb.ClientPublishMessage
	(*ClientPushMessage)(nil),                 // 1: pb.ClientPushMessage
	(*ClientSubscribeMessage)(nil),            // 2: pb.ClientSubscribeMessage
	(*ClientSubscriptionsMessage)(nil),        // 3: pb.ClientSubscriptionsMessage
	(*ClientAddrRequestMessage)(nil),          // 4: pb.ClientAddrRequestMessage
	(*ClientAddrResponseMessage)(nil),         // 5: pb.ClientAddrResponseMessage
	(*ClientAddrResponseMessage_Success)(nil), // 6: pb.ClientAddrResponseMessage.Success
}
var file_protocols_proto_depIdxs = []int32{
	6, // 0: pb.ClientAddrResponseMessage.success:type_name -> pb.ClientAddrResponseMessage.Success
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protocols_proto_init() }
func file_protocols_proto_init() {
	if File_protocols_proto != nil {
		return
	}
	file_protocols_proto_msgTypes[5].OneofWrappers = []any{
		(*ClientAddrResponseMessage_Success_)(nil),
		(*ClientAddrResponseMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocols_proto_rawDesc), len(file_protocols_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocols_proto_goTypes,
		DependencyIndexes: file_protocols_proto_depIdxs,
		MessageInfos:      file_protocols_proto_msgTypes,
	}.Build()
	File_protocols_proto = out.File
	file_protocols_proto_goTypes = nil
	file_protocols_proto_depIdxs = nil
}
