// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.2
// source: protocols.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushMessage_MessageType int32

const (
	PushMessage_UNSPECIFIED PushMessage_MessageType = 0
	PushMessage_BROADCAST   PushMessage_MessageType = 1
	PushMessage_SUBSCRIBE   PushMessage_MessageType = 2
	PushMessage_UNSUBSCRIBE PushMessage_MessageType = 3
)

// Enum value maps for PushMessage_MessageType.
var (
	PushMessage_MessageType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "BROADCAST",
		2: "SUBSCRIBE",
		3: "UNSUBSCRIBE",
	}
	PushMessage_MessageType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"BROADCAST":   1,
		"SUBSCRIBE":   2,
		"UNSUBSCRIBE": 3,
	}
)

func (x PushMessage_MessageType) Enum() *PushMessage_MessageType {
	p := new(PushMessage_MessageType)
	*p = x
	return p
}

func (x PushMessage_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushMessage_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_protocols_proto_enumTypes[0].Descriptor()
}

func (PushMessage_MessageType) Type() protoreflect.EnumType {
	return &file_protocols_proto_enumTypes[0]
}

func (x PushMessage_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushMessage_MessageType.Descriptor instead.
func (PushMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{8, 0}
}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*Response_Success
	//	*Response_Error
	//	*Response_SubscriptionsResponse
	//	*Response_AddrResponse
	//	*Response_PostBondResponse
	//	*Response_DiscoveryResponse
	Response      isResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_protocols_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetResponse() isResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *Response) GetSuccess() *Success {
	if x != nil {
		if x, ok := x.Response.(*Response_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *Response) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*Response_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Response) GetSubscriptionsResponse() *SubscriptionsResponse {
	if x != nil {
		if x, ok := x.Response.(*Response_SubscriptionsResponse); ok {
			return x.SubscriptionsResponse
		}
	}
	return nil
}

func (x *Response) GetAddrResponse() *ClientAddrResponse {
	if x != nil {
		if x, ok := x.Response.(*Response_AddrResponse); ok {
			return x.AddrResponse
		}
	}
	return nil
}

func (x *Response) GetPostBondResponse() *PostBondResponse {
	if x != nil {
		if x, ok := x.Response.(*Response_PostBondResponse); ok {
			return x.PostBondResponse
		}
	}
	return nil
}

func (x *Response) GetDiscoveryResponse() *DiscoveryResponse {
	if x != nil {
		if x, ok := x.Response.(*Response_DiscoveryResponse); ok {
			return x.DiscoveryResponse
		}
	}
	return nil
}

type isResponse_Response interface {
	isResponse_Response()
}

type Response_Success struct {
	Success *Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type Response_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type Response_SubscriptionsResponse struct {
	SubscriptionsResponse *SubscriptionsResponse `protobuf:"bytes,3,opt,name=subscriptions_response,json=subscriptionsResponse,proto3,oneof"`
}

type Response_AddrResponse struct {
	AddrResponse *ClientAddrResponse `protobuf:"bytes,4,opt,name=addr_response,json=addrResponse,proto3,oneof"`
}

type Response_PostBondResponse struct {
	PostBondResponse *PostBondResponse `protobuf:"bytes,5,opt,name=post_bond_response,json=postBondResponse,proto3,oneof"`
}

type Response_DiscoveryResponse struct {
	DiscoveryResponse *DiscoveryResponse `protobuf:"bytes,6,opt,name=discovery_response,json=discoveryResponse,proto3,oneof"`
}

func (*Response_Success) isResponse_Response() {}

func (*Response_Error) isResponse_Response() {}

func (*Response_SubscriptionsResponse) isResponse_Response() {}

func (*Response_AddrResponse) isResponse_Response() {}

func (*Response_PostBondResponse) isResponse_Response() {}

func (*Response_DiscoveryResponse) isResponse_Response() {}

type Success struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Success) Reset() {
	*x = Success{}
	mi := &file_protocols_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Success) ProtoMessage() {}

func (x *Success) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Success.ProtoReflect.Descriptor instead.
func (*Success) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{1}
}

// UnauthorizedError is returned when making a request on a protocol for which
// the peer is not authorized.
type UnauthorizedError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnauthorizedError) Reset() {
	*x = UnauthorizedError{}
	mi := &file_protocols_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnauthorizedError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnauthorizedError) ProtoMessage() {}

func (x *UnauthorizedError) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnauthorizedError.ProtoReflect.Descriptor instead.
func (*UnauthorizedError) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{2}
}

// CounterpartyNotFoundError is returned during a client initiate relay request
// to indicate that the relay was unable to be setup because the counterparty
// was not found.
type CounterpartyNotFoundError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CounterpartyNotFoundError) Reset() {
	*x = CounterpartyNotFoundError{}
	mi := &file_protocols_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterpartyNotFoundError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterpartyNotFoundError) ProtoMessage() {}

func (x *CounterpartyNotFoundError) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterpartyNotFoundError.ProtoReflect.Descriptor instead.
func (*CounterpartyNotFoundError) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{3}
}

// CounterpartyRejectedError is returned during a client initiate relay request
// to indicate that the relay was unable to be setup because the counterparty
// rejected the relay request.
type CounterpartyRejectedError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CounterpartyRejectedError) Reset() {
	*x = CounterpartyRejectedError{}
	mi := &file_protocols_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterpartyRejectedError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterpartyRejectedError) ProtoMessage() {}

func (x *CounterpartyRejectedError) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterpartyRejectedError.ProtoReflect.Descriptor instead.
func (*CounterpartyRejectedError) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{4}
}

// PostBondError is a type containing specific error information for the
// PostBonds protocol.
type PostBondError struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InvalidBondIndex uint32                 `protobuf:"varint,1,opt,name=invalidBondIndex,proto3" json:"invalidBondIndex,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PostBondError) Reset() {
	*x = PostBondError{}
	mi := &file_protocols_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostBondError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBondError) ProtoMessage() {}

func (x *PostBondError) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBondError.ProtoReflect.Descriptor instead.
func (*PostBondError) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{5}
}

func (x *PostBondError) GetInvalidBondIndex() uint32 {
	if x != nil {
		return x.InvalidBondIndex
	}
	return 0
}

type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Error:
	//
	//	*Error_Unauthorized
	//	*Error_PostBondError
	//	*Error_Message
	//	*Error_CpNotFoundError
	//	*Error_CpRejectedError
	Error         isError_Error `protobuf_oneof:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_protocols_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetError() isError_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Error) GetUnauthorized() *UnauthorizedError {
	if x != nil {
		if x, ok := x.Error.(*Error_Unauthorized); ok {
			return x.Unauthorized
		}
	}
	return nil
}

func (x *Error) GetPostBondError() *PostBondError {
	if x != nil {
		if x, ok := x.Error.(*Error_PostBondError); ok {
			return x.PostBondError
		}
	}
	return nil
}

func (x *Error) GetMessage() string {
	if x != nil {
		if x, ok := x.Error.(*Error_Message); ok {
			return x.Message
		}
	}
	return ""
}

func (x *Error) GetCpNotFoundError() *CounterpartyNotFoundError {
	if x != nil {
		if x, ok := x.Error.(*Error_CpNotFoundError); ok {
			return x.CpNotFoundError
		}
	}
	return nil
}

func (x *Error) GetCpRejectedError() *CounterpartyRejectedError {
	if x != nil {
		if x, ok := x.Error.(*Error_CpRejectedError); ok {
			return x.CpRejectedError
		}
	}
	return nil
}

type isError_Error interface {
	isError_Error()
}

type Error_Unauthorized struct {
	Unauthorized *UnauthorizedError `protobuf:"bytes,1,opt,name=unauthorized,proto3,oneof"`
}

type Error_PostBondError struct {
	PostBondError *PostBondError `protobuf:"bytes,2,opt,name=post_bond_error,json=postBondError,proto3,oneof"`
}

type Error_Message struct {
	Message string `protobuf:"bytes,3,opt,name=message,proto3,oneof"`
}

type Error_CpNotFoundError struct {
	CpNotFoundError *CounterpartyNotFoundError `protobuf:"bytes,4,opt,name=cp_not_found_error,json=cpNotFoundError,proto3,oneof"`
}

type Error_CpRejectedError struct {
	CpRejectedError *CounterpartyRejectedError `protobuf:"bytes,5,opt,name=cp_rejected_error,json=cpRejectedError,proto3,oneof"`
}

func (*Error_Unauthorized) isError_Error() {}

func (*Error_PostBondError) isError_Error() {}

func (*Error_Message) isError_Error() {}

func (*Error_CpNotFoundError) isError_Error() {}

func (*Error_CpRejectedError) isError_Error() {}

// PublishRequest is sent by a client to publish a message to a topic.
type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_protocols_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{7}
}

func (x *PublishRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// PushMessage is sent by the server to push a message to a subscribed client.
// Used with the PushProtocol.
type PushMessage struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	MessageType   PushMessage_MessageType `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=pb.PushMessage_MessageType" json:"message_type,omitempty"`
	Topic         string                  `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Data          []byte                  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`     // Only populated for BROADCAST messages
	Sender        []byte                  `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"` // The peer who sent the message or performed the subscription action
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessage) Reset() {
	*x = PushMessage{}
	mi := &file_protocols_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessage) ProtoMessage() {}

func (x *PushMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessage.ProtoReflect.Descriptor instead.
func (*PushMessage) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{8}
}

func (x *PushMessage) GetMessageType() PushMessage_MessageType {
	if x != nil {
		return x.MessageType
	}
	return PushMessage_UNSPECIFIED
}

func (x *PushMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PushMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PushMessage) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

// SubscribeRequest is sent by a client to subscribe or unsubscribe from
// a topic.
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Subscribe     bool                   `protobuf:"varint,2,opt,name=subscribe,proto3" json:"subscribe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_protocols_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubscribeRequest) GetSubscribe() bool {
	if x != nil {
		return x.Subscribe
	}
	return false
}

// SubscriptionsResponse is sent by a tatanka node informing the client
// which topics they are subscribed to.
type SubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []string               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionsResponse) Reset() {
	*x = SubscriptionsResponse{}
	mi := &file_protocols_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionsResponse) ProtoMessage() {}

func (x *SubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{10}
}

func (x *SubscriptionsResponse) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

// ClientAddrRequest is sent by a client to request the addresses of another peer.
type ClientAddrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // peer.ID serialized as bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientAddrRequest) Reset() {
	*x = ClientAddrRequest{}
	mi := &file_protocols_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAddrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAddrRequest) ProtoMessage() {}

func (x *ClientAddrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAddrRequest.ProtoReflect.Descriptor instead.
func (*ClientAddrRequest) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{11}
}

func (x *ClientAddrRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

// ClientAddrResponse is the response containing the multiaddresses of a peer or an error.
// Used with the ClientAddr.
type ClientAddrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addrs         [][]byte               `protobuf:"bytes,1,rep,name=addrs,proto3" json:"addrs,omitempty"` // multiaddrs serialized as bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientAddrResponse) Reset() {
	*x = ClientAddrResponse{}
	mi := &file_protocols_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAddrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAddrResponse) ProtoMessage() {}

func (x *ClientAddrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAddrResponse.ProtoReflect.Descriptor instead.
func (*ClientAddrResponse) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{12}
}

func (x *ClientAddrResponse) GetAddrs() [][]byte {
	if x != nil {
		return x.Addrs
	}
	return nil
}

type Bond struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetID       uint32                 `protobuf:"varint,1,opt,name=assetID,proto3" json:"assetID,omitempty"`
	BondID        []byte                 `protobuf:"bytes,2,opt,name=bondID,proto3" json:"bondID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bond) Reset() {
	*x = Bond{}
	mi := &file_protocols_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bond) ProtoMessage() {}

func (x *Bond) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bond.ProtoReflect.Descriptor instead.
func (*Bond) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{13}
}

func (x *Bond) GetAssetID() uint32 {
	if x != nil {
		return x.AssetID
	}
	return 0
}

func (x *Bond) GetBondID() []byte {
	if x != nil {
		return x.BondID
	}
	return nil
}

type PostBondRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bonds         []*Bond                `protobuf:"bytes,1,rep,name=bonds,proto3" json:"bonds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostBondRequest) Reset() {
	*x = PostBondRequest{}
	mi := &file_protocols_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostBondRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBondRequest) ProtoMessage() {}

func (x *PostBondRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBondRequest.ProtoReflect.Descriptor instead.
func (*PostBondRequest) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{14}
}

func (x *PostBondRequest) GetBonds() []*Bond {
	if x != nil {
		return x.Bonds
	}
	return nil
}

type PostBondResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BondStrength  uint32                 `protobuf:"varint,1,opt,name=bondStrength,proto3" json:"bondStrength,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostBondResponse) Reset() {
	*x = PostBondResponse{}
	mi := &file_protocols_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostBondResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBondResponse) ProtoMessage() {}

func (x *PostBondResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBondResponse.ProtoReflect.Descriptor instead.
func (*PostBondResponse) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{15}
}

func (x *PostBondResponse) GetBondStrength() uint32 {
	if x != nil {
		return x.BondStrength
	}
	return 0
}

// PeerInfo contains information about a single peer.
type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`       // peer.ID serialized as bytes
	Addrs         [][]byte               `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"` // multiaddrs serialized as bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_protocols_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{16}
}

func (x *PeerInfo) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *PeerInfo) GetAddrs() [][]byte {
	if x != nil {
		return x.Addrs
	}
	return nil
}

// DiscoveryResponse contains a list of peers for discovery.
type DiscoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryResponse) Reset() {
	*x = DiscoveryResponse{}
	mi := &file_protocols_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryResponse) ProtoMessage() {}

func (x *DiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryResponse.ProtoReflect.Descriptor instead.
func (*DiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{17}
}

func (x *DiscoveryResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

// ClientRelayMessageRequest is a client originating request to send a
// message to another client.
type ClientRelayMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerID        []byte                 `protobuf:"bytes,1,opt,name=peerID,proto3" json:"peerID,omitempty"` // peer.ID serialized as bytes
	Message       []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRelayMessageRequest) Reset() {
	*x = ClientRelayMessageRequest{}
	mi := &file_protocols_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRelayMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRelayMessageRequest) ProtoMessage() {}

func (x *ClientRelayMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRelayMessageRequest.ProtoReflect.Descriptor instead.
func (*ClientRelayMessageRequest) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{18}
}

func (x *ClientRelayMessageRequest) GetPeerID() []byte {
	if x != nil {
		return x.PeerID
	}
	return nil
}

func (x *ClientRelayMessageRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

// ClientRelayMessageResponse is the response to a ClientRelayMessageRequest.
type ClientRelayMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ClientRelayMessageResponse_Message
	//	*ClientRelayMessageResponse_Error
	Response      isClientRelayMessageResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRelayMessageResponse) Reset() {
	*x = ClientRelayMessageResponse{}
	mi := &file_protocols_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRelayMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRelayMessageResponse) ProtoMessage() {}

func (x *ClientRelayMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRelayMessageResponse.ProtoReflect.Descriptor instead.
func (*ClientRelayMessageResponse) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{19}
}

func (x *ClientRelayMessageResponse) GetResponse() isClientRelayMessageResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ClientRelayMessageResponse) GetMessage() []byte {
	if x != nil {
		if x, ok := x.Response.(*ClientRelayMessageResponse_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *ClientRelayMessageResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*ClientRelayMessageResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isClientRelayMessageResponse_Response interface {
	isClientRelayMessageResponse_Response()
}

type ClientRelayMessageResponse_Message struct {
	Message []byte `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type ClientRelayMessageResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ClientRelayMessageResponse_Message) isClientRelayMessageResponse_Response() {}

func (*ClientRelayMessageResponse_Error) isClientRelayMessageResponse_Response() {}

// TatankaRelayMessageRequest is a tatanka node originating request to a client
// to notify them that another client is sending them a message.
type TatankaRelayMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerID        []byte                 `protobuf:"bytes,1,opt,name=peerID,proto3" json:"peerID,omitempty"` // peer.ID serialized as bytes
	Message       []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TatankaRelayMessageRequest) Reset() {
	*x = TatankaRelayMessageRequest{}
	mi := &file_protocols_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TatankaRelayMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TatankaRelayMessageRequest) ProtoMessage() {}

func (x *TatankaRelayMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TatankaRelayMessageRequest.ProtoReflect.Descriptor instead.
func (*TatankaRelayMessageRequest) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{20}
}

func (x *TatankaRelayMessageRequest) GetPeerID() []byte {
	if x != nil {
		return x.PeerID
	}
	return nil
}

func (x *TatankaRelayMessageRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

// TatankaRelayMessageResponse is the response to a TatankaRelayMessageRequest.
type TatankaRelayMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*TatankaRelayMessageResponse_Message
	//	*TatankaRelayMessageResponse_Error
	Response      isTatankaRelayMessageResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TatankaRelayMessageResponse) Reset() {
	*x = TatankaRelayMessageResponse{}
	mi := &file_protocols_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TatankaRelayMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TatankaRelayMessageResponse) ProtoMessage() {}

func (x *TatankaRelayMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TatankaRelayMessageResponse.ProtoReflect.Descriptor instead.
func (*TatankaRelayMessageResponse) Descriptor() ([]byte, []int) {
	return file_protocols_proto_rawDescGZIP(), []int{21}
}

func (x *TatankaRelayMessageResponse) GetResponse() isTatankaRelayMessageResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *TatankaRelayMessageResponse) GetMessage() []byte {
	if x != nil {
		if x, ok := x.Response.(*TatankaRelayMessageResponse_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *TatankaRelayMessageResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*TatankaRelayMessageResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isTatankaRelayMessageResponse_Response interface {
	isTatankaRelayMessageResponse_Response()
}

type TatankaRelayMessageResponse_Message struct {
	Message []byte `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type TatankaRelayMessageResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*TatankaRelayMessageResponse_Message) isTatankaRelayMessageResponse_Response() {}

func (*TatankaRelayMessageResponse_Error) isTatankaRelayMessageResponse_Response() {}

var File_protocols_proto protoreflect.FileDescriptor

const file_protocols_proto_rawDesc = "" +
	"\n" +
	"\x0fprotocols.proto\x12\x02pb\"\x83\x03\n" +
	"\bResponse\x12'\n" +
	"\asuccess\x18\x01 \x01(\v2\v.pb.SuccessH\x00R\asuccess\x12!\n" +
	"\x05error\x18\x02 \x01(\v2\t.pb.ErrorH\x00R\x05error\x12R\n" +
	"\x16subscriptions_response\x18\x03 \x01(\v2\x19.pb.SubscriptionsResponseH\x00R\x15subscriptionsResponse\x12=\n" +
	"\raddr_response\x18\x04 \x01(\v2\x16.pb.ClientAddrResponseH\x00R\faddrResponse\x12D\n" +
	"\x12post_bond_response\x18\x05 \x01(\v2\x14.pb.PostBondResponseH\x00R\x10postBondResponse\x12F\n" +
	"\x12discovery_response\x18\x06 \x01(\v2\x15.pb.DiscoveryResponseH\x00R\x11discoveryResponseB\n" +
	"\n" +
	"\bresponse\"\t\n" +
	"\aSuccess\"\x13\n" +
	"\x11UnauthorizedError\"\x1b\n" +
	"\x19CounterpartyNotFoundError\"\x1b\n" +
	"\x19CounterpartyRejectedError\";\n" +
	"\rPostBondError\x12*\n" +
	"\x10invalidBondIndex\x18\x01 \x01(\rR\x10invalidBondIndex\"\xc1\x02\n" +
	"\x05Error\x12;\n" +
	"\funauthorized\x18\x01 \x01(\v2\x15.pb.UnauthorizedErrorH\x00R\funauthorized\x12;\n" +
	"\x0fpost_bond_error\x18\x02 \x01(\v2\x11.pb.PostBondErrorH\x00R\rpostBondError\x12\x1a\n" +
	"\amessage\x18\x03 \x01(\tH\x00R\amessage\x12L\n" +
	"\x12cp_not_found_error\x18\x04 \x01(\v2\x1d.pb.CounterpartyNotFoundErrorH\x00R\x0fcpNotFoundError\x12K\n" +
	"\x11cp_rejected_error\x18\x05 \x01(\v2\x1d.pb.CounterpartyRejectedErrorH\x00R\x0fcpRejectedErrorB\a\n" +
	"\x05error\":\n" +
	"\x0ePublishRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xde\x01\n" +
	"\vPushMessage\x12>\n" +
	"\fmessage_type\x18\x01 \x01(\x0e2\x1b.pb.PushMessage.MessageTypeR\vmessageType\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x16\n" +
	"\x06sender\x18\x04 \x01(\fR\x06sender\"M\n" +
	"\vMessageType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\r\n" +
	"\tBROADCAST\x10\x01\x12\r\n" +
	"\tSUBSCRIBE\x10\x02\x12\x0f\n" +
	"\vUNSUBSCRIBE\x10\x03\"F\n" +
	"\x10SubscribeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tsubscribe\x18\x02 \x01(\bR\tsubscribe\"/\n" +
	"\x15SubscriptionsResponse\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topics\"#\n" +
	"\x11ClientAddrRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"*\n" +
	"\x12ClientAddrResponse\x12\x14\n" +
	"\x05addrs\x18\x01 \x03(\fR\x05addrs\"8\n" +
	"\x04Bond\x12\x18\n" +
	"\aassetID\x18\x01 \x01(\rR\aassetID\x12\x16\n" +
	"\x06bondID\x18\x02 \x01(\fR\x06bondID\"1\n" +
	"\x0fPostBondRequest\x12\x1e\n" +
	"\x05bonds\x18\x01 \x03(\v2\b.pb.BondR\x05bonds\"6\n" +
	"\x10PostBondResponse\x12\"\n" +
	"\fbondStrength\x18\x01 \x01(\rR\fbondStrength\"0\n" +
	"\bPeerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\fR\x05addrs\"7\n" +
	"\x11DiscoveryResponse\x12\"\n" +
	"\x05peers\x18\x01 \x03(\v2\f.pb.PeerInfoR\x05peers\"M\n" +
	"\x19ClientRelayMessageRequest\x12\x16\n" +
	"\x06peerID\x18\x01 \x01(\fR\x06peerID\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage\"g\n" +
	"\x1aClientRelayMessageResponse\x12\x1a\n" +
	"\amessage\x18\x01 \x01(\fH\x00R\amessage\x12!\n" +
	"\x05error\x18\x02 \x01(\v2\t.pb.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"N\n" +
	"\x1aTatankaRelayMessageRequest\x12\x16\n" +
	"\x06peerID\x18\x01 \x01(\fR\x06peerID\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage\"h\n" +
	"\x1bTatankaRelayMessageResponse\x12\x1a\n" +
	"\amessage\x18\x01 \x01(\fH\x00R\amessage\x12!\n" +
	"\x05error\x18\x02 \x01(\v2\t.pb.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponseB.Z,github.com/martonp/tatanka-mesh/protocols/pbb\x06proto3"

var (
	file_protocols_proto_rawDescOnce sync.Once
	file_protocols_proto_rawDescData []byte
)

func file_protocols_proto_rawDescGZIP() []byte {
	file_protocols_proto_rawDescOnce.Do(func() {
		file_protocols_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocols_proto_rawDesc), len(file_protocols_proto_rawDesc)))
	})
	return file_protocols_proto_rawDescData
}

var file_protocols_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protocols_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_protocols_proto_goTypes = []any{
	(PushMessage_MessageType)(0),        // 0: pb.PushMessage.MessageType
	(*Response)(nil),                    // 1: pb.Response
	(*Success)(nil),                     // 2: pb.Success
	(*UnauthorizedError)(nil),           // 3: pb.UnauthorizedError
	(*CounterpartyNotFoundError)(nil),   // 4: pb.CounterpartyNotFoundError
	(*CounterpartyRejectedError)(nil),   // 5: pb.CounterpartyRejectedError
	(*PostBondError)(nil),               // 6: pb.PostBondError
	(*Error)(nil),                       // 7: pb.Error
	(*PublishRequest)(nil),              // 8: pb.PublishRequest
	(*PushMessage)(nil),                 // 9: pb.PushMessage
	(*SubscribeRequest)(nil),            // 10: pb.SubscribeRequest
	(*SubscriptionsResponse)(nil),       // 11: pb.SubscriptionsResponse
	(*ClientAddrRequest)(nil),           // 12: pb.ClientAddrRequest
	(*ClientAddrResponse)(nil),          // 13: pb.ClientAddrResponse
	(*Bond)(nil),                        // 14: pb.Bond
	(*PostBondRequest)(nil),             // 15: pb.PostBondRequest
	(*PostBondResponse)(nil),            // 16: pb.PostBondResponse
	(*PeerInfo)(nil),                    // 17: pb.PeerInfo
	(*DiscoveryResponse)(nil),           // 18: pb.DiscoveryResponse
	(*ClientRelayMessageRequest)(nil),   // 19: pb.ClientRelayMessageRequest
	(*ClientRelayMessageResponse)(nil),  // 20: pb.ClientRelayMessageResponse
	(*TatankaRelayMessageRequest)(nil),  // 21: pb.TatankaRelayMessageRequest
	(*TatankaRelayMessageResponse)(nil), // 22: pb.TatankaRelayMessageResponse
}
var file_protocols_proto_depIdxs = []int32{
	2,  // 0: pb.Response.success:type_name -> pb.Success
	7,  // 1: pb.Response.error:type_name -> pb.Error
	11, // 2: pb.Response.subscriptions_response:type_name -> pb.SubscriptionsResponse
	13, // 3: pb.Response.addr_response:type_name -> pb.ClientAddrResponse
	16, // 4: pb.Response.post_bond_response:type_name -> pb.PostBondResponse
	18, // 5: pb.Response.discovery_response:type_name -> pb.DiscoveryResponse
	3,  // 6: pb.Error.unauthorized:type_name -> pb.UnauthorizedError
	6,  // 7: pb.Error.post_bond_error:type_name -> pb.PostBondError
	4,  // 8: pb.Error.cp_not_found_error:type_name -> pb.CounterpartyNotFoundError
	5,  // 9: pb.Error.cp_rejected_error:type_name -> pb.CounterpartyRejectedError
	0,  // 10: pb.PushMessage.message_type:type_name -> pb.PushMessage.MessageType
	14, // 11: pb.PostBondRequest.bonds:type_name -> pb.Bond
	17, // 12: pb.DiscoveryResponse.peers:type_name -> pb.PeerInfo
	7,  // 13: pb.ClientRelayMessageResponse.error:type_name -> pb.Error
	7,  // 14: pb.TatankaRelayMessageResponse.error:type_name -> pb.Error
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_protocols_proto_init() }
func file_protocols_proto_init() {
	if File_protocols_proto != nil {
		return
	}
	file_protocols_proto_msgTypes[0].OneofWrappers = []any{
		(*Response_Success)(nil),
		(*Response_Error)(nil),
		(*Response_SubscriptionsResponse)(nil),
		(*Response_AddrResponse)(nil),
		(*Response_PostBondResponse)(nil),
		(*Response_DiscoveryResponse)(nil),
	}
	file_protocols_proto_msgTypes[6].OneofWrappers = []any{
		(*Error_Unauthorized)(nil),
		(*Error_PostBondError)(nil),
		(*Error_Message)(nil),
		(*Error_CpNotFoundError)(nil),
		(*Error_CpRejectedError)(nil),
	}
	file_protocols_proto_msgTypes[19].OneofWrappers = []any{
		(*ClientRelayMessageResponse_Message)(nil),
		(*ClientRelayMessageResponse_Error)(nil),
	}
	file_protocols_proto_msgTypes[21].OneofWrappers = []any{
		(*TatankaRelayMessageResponse_Message)(nil),
		(*TatankaRelayMessageResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocols_proto_rawDesc), len(file_protocols_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocols_proto_goTypes,
		DependencyIndexes: file_protocols_proto_depIdxs,
		EnumInfos:         file_protocols_proto_enumTypes,
		MessageInfos:      file_protocols_proto_msgTypes,
	}.Build()
	File_protocols_proto = out.File
	file_protocols_proto_goTypes = nil
	file_protocols_proto_depIdxs = nil
}
