// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: messages.proto

package clientpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Error:
	//
	//	*Error_Message
	//	*Error_NoEncryptionKeyError
	Error         isError_Error `protobuf_oneof:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetError() isError_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Error) GetMessage() string {
	if x != nil {
		if x, ok := x.Error.(*Error_Message); ok {
			return x.Message
		}
	}
	return ""
}

func (x *Error) GetNoEncryptionKeyError() *NoEncryptionKeyError {
	if x != nil {
		if x, ok := x.Error.(*Error_NoEncryptionKeyError); ok {
			return x.NoEncryptionKeyError
		}
	}
	return nil
}

type isError_Error interface {
	isError_Error()
}

type Error_Message struct {
	Message string `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type Error_NoEncryptionKeyError struct {
	NoEncryptionKeyError *NoEncryptionKeyError `protobuf:"bytes,2,opt,name=no_encryption_key_error,json=noEncryptionKeyError,proto3,oneof"`
}

func (*Error_Message) isError_Error() {}

func (*Error_NoEncryptionKeyError) isError_Error() {}

type NoEncryptionKeyError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoEncryptionKeyError) Reset() {
	*x = NoEncryptionKeyError{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoEncryptionKeyError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoEncryptionKeyError) ProtoMessage() {}

func (x *NoEncryptionKeyError) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoEncryptionKeyError.ProtoReflect.Descriptor instead.
func (*NoEncryptionKeyError) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *HandshakeRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *HandshakeRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type HandshakeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*HandshakeResponse_PublicKey
	//	*HandshakeResponse_Error
	Result        isHandshakeResponse_Result `protobuf_oneof:"result"`
	Signature     []byte                     `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Nonce         []byte                     `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *HandshakeResponse) GetResult() isHandshakeResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *HandshakeResponse) GetPublicKey() []byte {
	if x != nil {
		if x, ok := x.Result.(*HandshakeResponse_PublicKey); ok {
			return x.PublicKey
		}
	}
	return nil
}

func (x *HandshakeResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*HandshakeResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *HandshakeResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *HandshakeResponse) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type isHandshakeResponse_Result interface {
	isHandshakeResponse_Result()
}

type HandshakeResponse_PublicKey struct {
	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3,oneof"`
}

type HandshakeResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*HandshakeResponse_PublicKey) isHandshakeResponse_Result() {}

func (*HandshakeResponse_Error) isHandshakeResponse_Result() {}

type MessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []byte                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRequest) Reset() {
	*x = MessageRequest{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRequest) ProtoMessage() {}

func (x *MessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRequest.ProtoReflect.Descriptor instead.
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *MessageRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type MessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*MessageResponse_Message
	//	*MessageResponse_Error
	Response      isMessageResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *MessageResponse) GetResponse() isMessageResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *MessageResponse) GetMessage() []byte {
	if x != nil {
		if x, ok := x.Response.(*MessageResponse_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *MessageResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Response.(*MessageResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isMessageResponse_Response interface {
	isMessageResponse_Response()
}

type MessageResponse_Message struct {
	Message []byte `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type MessageResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*MessageResponse_Message) isMessageResponse_Response() {}

func (*MessageResponse_Error) isMessageResponse_Response() {}

type ClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*ClientRequest_HandshakeRequest
	//	*ClientRequest_MessageRequest
	Request       isClientRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ClientRequest) GetRequest() isClientRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ClientRequest) GetHandshakeRequest() *HandshakeRequest {
	if x != nil {
		if x, ok := x.Request.(*ClientRequest_HandshakeRequest); ok {
			return x.HandshakeRequest
		}
	}
	return nil
}

func (x *ClientRequest) GetMessageRequest() *MessageRequest {
	if x != nil {
		if x, ok := x.Request.(*ClientRequest_MessageRequest); ok {
			return x.MessageRequest
		}
	}
	return nil
}

type isClientRequest_Request interface {
	isClientRequest_Request()
}

type ClientRequest_HandshakeRequest struct {
	HandshakeRequest *HandshakeRequest `protobuf:"bytes,1,opt,name=handshake_request,json=handshakeRequest,proto3,oneof"`
}

type ClientRequest_MessageRequest struct {
	MessageRequest *MessageRequest `protobuf:"bytes,2,opt,name=message_request,json=messageRequest,proto3,oneof"`
}

func (*ClientRequest_HandshakeRequest) isClientRequest_Request() {}

func (*ClientRequest_MessageRequest) isClientRequest_Request() {}

type ClientResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ClientResponse_HandshakeResponse
	//	*ClientResponse_MessageResponse
	Response      isClientResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientResponse) Reset() {
	*x = ClientResponse{}
	mi := &file_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientResponse) ProtoMessage() {}

func (x *ClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientResponse.ProtoReflect.Descriptor instead.
func (*ClientResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *ClientResponse) GetResponse() isClientResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ClientResponse) GetHandshakeResponse() *HandshakeResponse {
	if x != nil {
		if x, ok := x.Response.(*ClientResponse_HandshakeResponse); ok {
			return x.HandshakeResponse
		}
	}
	return nil
}

func (x *ClientResponse) GetMessageResponse() *MessageResponse {
	if x != nil {
		if x, ok := x.Response.(*ClientResponse_MessageResponse); ok {
			return x.MessageResponse
		}
	}
	return nil
}

type isClientResponse_Response interface {
	isClientResponse_Response()
}

type ClientResponse_HandshakeResponse struct {
	HandshakeResponse *HandshakeResponse `protobuf:"bytes,1,opt,name=handshake_response,json=handshakeResponse,proto3,oneof"`
}

type ClientResponse_MessageResponse struct {
	MessageResponse *MessageResponse `protobuf:"bytes,2,opt,name=message_response,json=messageResponse,proto3,oneof"`
}

func (*ClientResponse_HandshakeResponse) isClientResponse_Response() {}

func (*ClientResponse_MessageResponse) isClientResponse_Response() {}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\bclientpb\"\x85\x01\n" +
	"\x05Error\x12\x1a\n" +
	"\amessage\x18\x01 \x01(\tH\x00R\amessage\x12W\n" +
	"\x17no_encryption_key_error\x18\x02 \x01(\v2\x1e.clientpb.NoEncryptionKeyErrorH\x00R\x14noEncryptionKeyErrorB\a\n" +
	"\x05error\"\x16\n" +
	"\x14NoEncryptionKeyError\"e\n" +
	"\x10HandshakeRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"\x9b\x01\n" +
	"\x11HandshakeResponse\x12\x1f\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fH\x00R\tpublicKey\x12'\n" +
	"\x05error\x18\x02 \x01(\v2\x0f.clientpb.ErrorH\x00R\x05error\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\fR\x05nonceB\b\n" +
	"\x06result\"*\n" +
	"\x0eMessageRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\fR\amessage\"b\n" +
	"\x0fMessageResponse\x12\x1a\n" +
	"\amessage\x18\x01 \x01(\fH\x00R\amessage\x12'\n" +
	"\x05error\x18\x02 \x01(\v2\x0f.clientpb.ErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\xaa\x01\n" +
	"\rClientRequest\x12I\n" +
	"\x11handshake_request\x18\x01 \x01(\v2\x1a.clientpb.HandshakeRequestH\x00R\x10handshakeRequest\x12C\n" +
	"\x0fmessage_request\x18\x02 \x01(\v2\x18.clientpb.MessageRequestH\x00R\x0emessageRequestB\t\n" +
	"\arequest\"\xb2\x01\n" +
	"\x0eClientResponse\x12L\n" +
	"\x12handshake_response\x18\x01 \x01(\v2\x1b.clientpb.HandshakeResponseH\x00R\x11handshakeResponse\x12F\n" +
	"\x10message_response\x18\x02 \x01(\v2\x19.clientpb.MessageResponseH\x00R\x0fmessageResponseB\n" +
	"\n" +
	"\bresponseB4Z2github.com/martonp/tatanka-mesh/client/pb;clientpbb\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_messages_proto_goTypes = []any{
	(*Error)(nil),                // 0: clientpb.Error
	(*NoEncryptionKeyError)(nil), // 1: clientpb.NoEncryptionKeyError
	(*HandshakeRequest)(nil),     // 2: clientpb.HandshakeRequest
	(*HandshakeResponse)(nil),    // 3: clientpb.HandshakeResponse
	(*MessageRequest)(nil),       // 4: clientpb.MessageRequest
	(*MessageResponse)(nil),      // 5: clientpb.MessageResponse
	(*ClientRequest)(nil),        // 6: clientpb.ClientRequest
	(*ClientResponse)(nil),       // 7: clientpb.ClientResponse
}
var file_messages_proto_depIdxs = []int32{
	1, // 0: clientpb.Error.no_encryption_key_error:type_name -> clientpb.NoEncryptionKeyError
	0, // 1: clientpb.HandshakeResponse.error:type_name -> clientpb.Error
	0, // 2: clientpb.MessageResponse.error:type_name -> clientpb.Error
	2, // 3: clientpb.ClientRequest.handshake_request:type_name -> clientpb.HandshakeRequest
	4, // 4: clientpb.ClientRequest.message_request:type_name -> clientpb.MessageRequest
	3, // 5: clientpb.ClientResponse.handshake_response:type_name -> clientpb.HandshakeResponse
	5, // 6: clientpb.ClientResponse.message_response:type_name -> clientpb.MessageResponse
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	file_messages_proto_msgTypes[0].OneofWrappers = []any{
		(*Error_Message)(nil),
		(*Error_NoEncryptionKeyError)(nil),
	}
	file_messages_proto_msgTypes[3].OneofWrappers = []any{
		(*HandshakeResponse_PublicKey)(nil),
		(*HandshakeResponse_Error)(nil),
	}
	file_messages_proto_msgTypes[5].OneofWrappers = []any{
		(*MessageResponse_Message)(nil),
		(*MessageResponse_Error)(nil),
	}
	file_messages_proto_msgTypes[6].OneofWrappers = []any{
		(*ClientRequest_HandshakeRequest)(nil),
		(*ClientRequest_MessageRequest)(nil),
	}
	file_messages_proto_msgTypes[7].OneofWrappers = []any{
		(*ClientResponse_HandshakeResponse)(nil),
		(*ClientResponse_MessageResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
