// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: messages.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClientConnectionMsg is used internally by tatanka nodes to share client connection information.
type ClientConnectionMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                   // peer.ID serialized as bytes
	ReporterId    []byte                 `protobuf:"bytes,2,opt,name=reporter_id,json=reporterId,proto3" json:"reporter_id,omitempty"` // peer.ID serialized as bytes
	Connected     bool                   `protobuf:"varint,3,opt,name=connected,proto3" json:"connected,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConnectionMsg) Reset() {
	*x = ClientConnectionMsg{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConnectionMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConnectionMsg) ProtoMessage() {}

func (x *ClientConnectionMsg) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConnectionMsg.ProtoReflect.Descriptor instead.
func (*ClientConnectionMsg) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ClientConnectionMsg) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ClientConnectionMsg) GetReporterId() []byte {
	if x != nil {
		return x.ReporterId
	}
	return nil
}

func (x *ClientConnectionMsg) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *ClientConnectionMsg) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type TatankaForwardRelayRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InitiatorId    []byte                 `protobuf:"bytes,1,opt,name=initiator_id,json=initiatorId,proto3" json:"initiator_id,omitempty"`          // peer.ID serialized as bytes
	CounterpartyId []byte                 `protobuf:"bytes,2,opt,name=counterparty_id,json=counterpartyId,proto3" json:"counterparty_id,omitempty"` // peer.ID serialized as bytes
	Message        []byte                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TatankaForwardRelayRequest) Reset() {
	*x = TatankaForwardRelayRequest{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TatankaForwardRelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TatankaForwardRelayRequest) ProtoMessage() {}

func (x *TatankaForwardRelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TatankaForwardRelayRequest.ProtoReflect.Descriptor instead.
func (*TatankaForwardRelayRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *TatankaForwardRelayRequest) GetInitiatorId() []byte {
	if x != nil {
		return x.InitiatorId
	}
	return nil
}

func (x *TatankaForwardRelayRequest) GetCounterpartyId() []byte {
	if x != nil {
		return x.CounterpartyId
	}
	return nil
}

func (x *TatankaForwardRelayRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type TatankaForwardRelayResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*TatankaForwardRelayResponse_Success
	//	*TatankaForwardRelayResponse_ClientNotFound_
	//	*TatankaForwardRelayResponse_ClientRejected_
	//	*TatankaForwardRelayResponse_Error
	Response      isTatankaForwardRelayResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TatankaForwardRelayResponse) Reset() {
	*x = TatankaForwardRelayResponse{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TatankaForwardRelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TatankaForwardRelayResponse) ProtoMessage() {}

func (x *TatankaForwardRelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TatankaForwardRelayResponse.ProtoReflect.Descriptor instead.
func (*TatankaForwardRelayResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *TatankaForwardRelayResponse) GetResponse() isTatankaForwardRelayResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *TatankaForwardRelayResponse) GetSuccess() []byte {
	if x != nil {
		if x, ok := x.Response.(*TatankaForwardRelayResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *TatankaForwardRelayResponse) GetClientNotFound() *TatankaForwardRelayResponse_ClientNotFound {
	if x != nil {
		if x, ok := x.Response.(*TatankaForwardRelayResponse_ClientNotFound_); ok {
			return x.ClientNotFound
		}
	}
	return nil
}

func (x *TatankaForwardRelayResponse) GetClientRejected() *TatankaForwardRelayResponse_ClientRejected {
	if x != nil {
		if x, ok := x.Response.(*TatankaForwardRelayResponse_ClientRejected_); ok {
			return x.ClientRejected
		}
	}
	return nil
}

func (x *TatankaForwardRelayResponse) GetError() string {
	if x != nil {
		if x, ok := x.Response.(*TatankaForwardRelayResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isTatankaForwardRelayResponse_Response interface {
	isTatankaForwardRelayResponse_Response()
}

type TatankaForwardRelayResponse_Success struct {
	Success []byte `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type TatankaForwardRelayResponse_ClientNotFound_ struct {
	ClientNotFound *TatankaForwardRelayResponse_ClientNotFound `protobuf:"bytes,2,opt,name=client_not_found,json=clientNotFound,proto3,oneof"`
}

type TatankaForwardRelayResponse_ClientRejected_ struct {
	ClientRejected *TatankaForwardRelayResponse_ClientRejected `protobuf:"bytes,3,opt,name=client_rejected,json=clientRejected,proto3,oneof"`
}

type TatankaForwardRelayResponse_Error struct {
	Error string `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*TatankaForwardRelayResponse_Success) isTatankaForwardRelayResponse_Response() {}

func (*TatankaForwardRelayResponse_ClientNotFound_) isTatankaForwardRelayResponse_Response() {}

func (*TatankaForwardRelayResponse_ClientRejected_) isTatankaForwardRelayResponse_Response() {}

func (*TatankaForwardRelayResponse_Error) isTatankaForwardRelayResponse_Response() {}

type DiscoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryRequest) Reset() {
	*x = DiscoveryRequest{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryRequest) ProtoMessage() {}

func (x *DiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryRequest.ProtoReflect.Descriptor instead.
func (*DiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *DiscoveryRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type DiscoveryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*DiscoveryResponse_Success_
	//	*DiscoveryResponse_NotFound_
	Response      isDiscoveryResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryResponse) Reset() {
	*x = DiscoveryResponse{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryResponse) ProtoMessage() {}

func (x *DiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryResponse.ProtoReflect.Descriptor instead.
func (*DiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *DiscoveryResponse) GetResponse() isDiscoveryResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *DiscoveryResponse) GetSuccess() *DiscoveryResponse_Success {
	if x != nil {
		if x, ok := x.Response.(*DiscoveryResponse_Success_); ok {
			return x.Success
		}
	}
	return nil
}

func (x *DiscoveryResponse) GetNotFound() *DiscoveryResponse_NotFound {
	if x != nil {
		if x, ok := x.Response.(*DiscoveryResponse_NotFound_); ok {
			return x.NotFound
		}
	}
	return nil
}

type isDiscoveryResponse_Response interface {
	isDiscoveryResponse_Response()
}

type DiscoveryResponse_Success_ struct {
	Success *DiscoveryResponse_Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type DiscoveryResponse_NotFound_ struct {
	NotFound *DiscoveryResponse_NotFound `protobuf:"bytes,2,opt,name=not_found,json=notFound,proto3,oneof"`
}

func (*DiscoveryResponse_Success_) isDiscoveryResponse_Response() {}

func (*DiscoveryResponse_NotFound_) isDiscoveryResponse_Response() {}

type WhitelistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerIDs       [][]byte               `protobuf:"bytes,1,rep,name=peerIDs,proto3" json:"peerIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhitelistRequest) Reset() {
	*x = WhitelistRequest{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhitelistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistRequest) ProtoMessage() {}

func (x *WhitelistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistRequest.ProtoReflect.Descriptor instead.
func (*WhitelistRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *WhitelistRequest) GetPeerIDs() [][]byte {
	if x != nil {
		return x.PeerIDs
	}
	return nil
}

type WhitelistResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*WhitelistResponse_Success_
	//	*WhitelistResponse_Mismatch_
	Response      isWhitelistResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhitelistResponse) Reset() {
	*x = WhitelistResponse{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhitelistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistResponse) ProtoMessage() {}

func (x *WhitelistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistResponse.ProtoReflect.Descriptor instead.
func (*WhitelistResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *WhitelistResponse) GetResponse() isWhitelistResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *WhitelistResponse) GetSuccess() *WhitelistResponse_Success {
	if x != nil {
		if x, ok := x.Response.(*WhitelistResponse_Success_); ok {
			return x.Success
		}
	}
	return nil
}

func (x *WhitelistResponse) GetMismatch() *WhitelistResponse_Mismatch {
	if x != nil {
		if x, ok := x.Response.(*WhitelistResponse_Mismatch_); ok {
			return x.Mismatch
		}
	}
	return nil
}

type isWhitelistResponse_Response interface {
	isWhitelistResponse_Response()
}

type WhitelistResponse_Success_ struct {
	Success *WhitelistResponse_Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type WhitelistResponse_Mismatch_ struct {
	Mismatch *WhitelistResponse_Mismatch `protobuf:"bytes,2,opt,name=mismatch,proto3,oneof"`
}

func (*WhitelistResponse_Success_) isWhitelistResponse_Response() {}

func (*WhitelistResponse_Mismatch_) isWhitelistResponse_Response() {}

type TatankaForwardRelayResponse_ClientNotFound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TatankaForwardRelayResponse_ClientNotFound) Reset() {
	*x = TatankaForwardRelayResponse_ClientNotFound{}
	mi := &file_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TatankaForwardRelayResponse_ClientNotFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TatankaForwardRelayResponse_ClientNotFound) ProtoMessage() {}

func (x *TatankaForwardRelayResponse_ClientNotFound) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TatankaForwardRelayResponse_ClientNotFound.ProtoReflect.Descriptor instead.
func (*TatankaForwardRelayResponse_ClientNotFound) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2, 0}
}

type TatankaForwardRelayResponse_ClientRejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TatankaForwardRelayResponse_ClientRejected) Reset() {
	*x = TatankaForwardRelayResponse_ClientRejected{}
	mi := &file_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TatankaForwardRelayResponse_ClientRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TatankaForwardRelayResponse_ClientRejected) ProtoMessage() {}

func (x *TatankaForwardRelayResponse_ClientRejected) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TatankaForwardRelayResponse_ClientRejected.ProtoReflect.Descriptor instead.
func (*TatankaForwardRelayResponse_ClientRejected) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2, 1}
}

type DiscoveryResponse_Success struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addrs         [][]byte               `protobuf:"bytes,1,rep,name=addrs,proto3" json:"addrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryResponse_Success) Reset() {
	*x = DiscoveryResponse_Success{}
	mi := &file_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryResponse_Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryResponse_Success) ProtoMessage() {}

func (x *DiscoveryResponse_Success) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryResponse_Success.ProtoReflect.Descriptor instead.
func (*DiscoveryResponse_Success) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4, 0}
}

func (x *DiscoveryResponse_Success) GetAddrs() [][]byte {
	if x != nil {
		return x.Addrs
	}
	return nil
}

type DiscoveryResponse_NotFound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryResponse_NotFound) Reset() {
	*x = DiscoveryResponse_NotFound{}
	mi := &file_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryResponse_NotFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryResponse_NotFound) ProtoMessage() {}

func (x *DiscoveryResponse_NotFound) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryResponse_NotFound.ProtoReflect.Descriptor instead.
func (*DiscoveryResponse_NotFound) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4, 1}
}

type WhitelistResponse_Success struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhitelistResponse_Success) Reset() {
	*x = WhitelistResponse_Success{}
	mi := &file_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhitelistResponse_Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistResponse_Success) ProtoMessage() {}

func (x *WhitelistResponse_Success) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistResponse_Success.ProtoReflect.Descriptor instead.
func (*WhitelistResponse_Success) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6, 0}
}

type WhitelistResponse_Mismatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerIDs       [][]byte               `protobuf:"bytes,1,rep,name=peerIDs,proto3" json:"peerIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhitelistResponse_Mismatch) Reset() {
	*x = WhitelistResponse_Mismatch{}
	mi := &file_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhitelistResponse_Mismatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistResponse_Mismatch) ProtoMessage() {}

func (x *WhitelistResponse_Mismatch) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistResponse_Mismatch.ProtoReflect.Descriptor instead.
func (*WhitelistResponse_Mismatch) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6, 1}
}

func (x *WhitelistResponse_Mismatch) GetPeerIDs() [][]byte {
	if x != nil {
		return x.PeerIDs
	}
	return nil
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\x02pb\"\x82\x01\n" +
	"\x13ClientConnectionMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x1f\n" +
	"\vreporter_id\x18\x02 \x01(\fR\n" +
	"reporterId\x12\x1c\n" +
	"\tconnected\x18\x03 \x01(\bR\tconnected\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x82\x01\n" +
	"\x1aTatankaForwardRelayRequest\x12!\n" +
	"\finitiator_id\x18\x01 \x01(\fR\vinitiatorId\x12'\n" +
	"\x0fcounterparty_id\x18\x02 \x01(\fR\x0ecounterpartyId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\fR\amessage\"\xb8\x02\n" +
	"\x1bTatankaForwardRelayResponse\x12\x1a\n" +
	"\asuccess\x18\x01 \x01(\fH\x00R\asuccess\x12Z\n" +
	"\x10client_not_found\x18\x02 \x01(\v2..pb.TatankaForwardRelayResponse.ClientNotFoundH\x00R\x0eclientNotFound\x12Y\n" +
	"\x0fclient_rejected\x18\x03 \x01(\v2..pb.TatankaForwardRelayResponse.ClientRejectedH\x00R\x0eclientRejected\x12\x16\n" +
	"\x05error\x18\x04 \x01(\tH\x00R\x05error\x1a\x10\n" +
	"\x0eClientNotFound\x1a\x10\n" +
	"\x0eClientRejectedB\n" +
	"\n" +
	"\bresponse\"\"\n" +
	"\x10DiscoveryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"\xc6\x01\n" +
	"\x11DiscoveryResponse\x129\n" +
	"\asuccess\x18\x01 \x01(\v2\x1d.pb.DiscoveryResponse.SuccessH\x00R\asuccess\x12=\n" +
	"\tnot_found\x18\x02 \x01(\v2\x1e.pb.DiscoveryResponse.NotFoundH\x00R\bnotFound\x1a\x1f\n" +
	"\aSuccess\x12\x14\n" +
	"\x05addrs\x18\x01 \x03(\fR\x05addrs\x1a\n" +
	"\n" +
	"\bNotFoundB\n" +
	"\n" +
	"\bresponse\",\n" +
	"\x10WhitelistRequest\x12\x18\n" +
	"\apeerIDs\x18\x01 \x03(\fR\apeerIDs\"\xc9\x01\n" +
	"\x11WhitelistResponse\x129\n" +
	"\asuccess\x18\x01 \x01(\v2\x1d.pb.WhitelistResponse.SuccessH\x00R\asuccess\x12<\n" +
	"\bmismatch\x18\x02 \x01(\v2\x1e.pb.WhitelistResponse.MismatchH\x00R\bmismatch\x1a\t\n" +
	"\aSuccess\x1a$\n" +
	"\bMismatch\x12\x18\n" +
	"\apeerIDs\x18\x01 \x03(\fR\apeerIDsB\n" +
	"\n" +
	"\bresponseB,Z*github.com/martonp/tatanka-mesh/tatanka/pbb\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_messages_proto_goTypes = []any{
	(*ClientConnectionMsg)(nil),                        // 0: pb.ClientConnectionMsg
	(*TatankaForwardRelayRequest)(nil),                 // 1: pb.TatankaForwardRelayRequest
	(*TatankaForwardRelayResponse)(nil),                // 2: pb.TatankaForwardRelayResponse
	(*DiscoveryRequest)(nil),                           // 3: pb.DiscoveryRequest
	(*DiscoveryResponse)(nil),                          // 4: pb.DiscoveryResponse
	(*WhitelistRequest)(nil),                           // 5: pb.WhitelistRequest
	(*WhitelistResponse)(nil),                          // 6: pb.WhitelistResponse
	(*TatankaForwardRelayResponse_ClientNotFound)(nil), // 7: pb.TatankaForwardRelayResponse.ClientNotFound
	(*TatankaForwardRelayResponse_ClientRejected)(nil), // 8: pb.TatankaForwardRelayResponse.ClientRejected
	(*DiscoveryResponse_Success)(nil),                  // 9: pb.DiscoveryResponse.Success
	(*DiscoveryResponse_NotFound)(nil),                 // 10: pb.DiscoveryResponse.NotFound
	(*WhitelistResponse_Success)(nil),                  // 11: pb.WhitelistResponse.Success
	(*WhitelistResponse_Mismatch)(nil),                 // 12: pb.WhitelistResponse.Mismatch
}
var file_messages_proto_depIdxs = []int32{
	7,  // 0: pb.TatankaForwardRelayResponse.client_not_found:type_name -> pb.TatankaForwardRelayResponse.ClientNotFound
	8,  // 1: pb.TatankaForwardRelayResponse.client_rejected:type_name -> pb.TatankaForwardRelayResponse.ClientRejected
	9,  // 2: pb.DiscoveryResponse.success:type_name -> pb.DiscoveryResponse.Success
	10, // 3: pb.DiscoveryResponse.not_found:type_name -> pb.DiscoveryResponse.NotFound
	11, // 4: pb.WhitelistResponse.success:type_name -> pb.WhitelistResponse.Success
	12, // 5: pb.WhitelistResponse.mismatch:type_name -> pb.WhitelistResponse.Mismatch
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	file_messages_proto_msgTypes[2].OneofWrappers = []any{
		(*TatankaForwardRelayResponse_Success)(nil),
		(*TatankaForwardRelayResponse_ClientNotFound_)(nil),
		(*TatankaForwardRelayResponse_ClientRejected_)(nil),
		(*TatankaForwardRelayResponse_Error)(nil),
	}
	file_messages_proto_msgTypes[4].OneofWrappers = []any{
		(*DiscoveryResponse_Success_)(nil),
		(*DiscoveryResponse_NotFound_)(nil),
	}
	file_messages_proto_msgTypes[6].OneofWrappers = []any{
		(*WhitelistResponse_Success_)(nil),
		(*WhitelistResponse_Mismatch_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
